@Data_Organizer_Server_HostAddress = http://localhost:5205

### Отримати підсумок тексту від OpenAI API
POST {{Data_Organizer_Server_HostAddress}}/api/openai/summary
Content-Type: application/json
Authorization: Bearer YOUR_JWT_TOKEN

{
  "content": "Це приклад тексту, для якого потрібно створити короткий підсумок."
}

###
